# Generated by Django 3.0.8 on 2020-10-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201003_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
