# Generated by Django 3.0.8 on 2020-10-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
